### ISSUE TITLE
--no-sandbox error on Linux

### ISSUE THREAD

**Issue by muhammadhendro** [Eugeny/terminus#1266]
[https://i.imgur.com/TlfjOVg.png](https://i.imgur.com/TlfjOVg.png)

using kali linux 2019 xfce

very thanks

**Comment by Eugeny** [comment]
Fixed

**Comment by scardracs** [comment]
@Eugeny I'd suggest to prefer --in-process-gpu instead of --no-sandbox as this one disable completely electron sandbox features. The problem seems to be connected only to nvidia GPUs (and only if you use nvidia-drivers instead of nouveau)

**Comment by Eugeny** [comment]
@scardracs does `--in-process-gpu` actually solve the above issue?

**Comment by scardracs** [comment]
> @scardracs does `--in-process-gpu` actually solve the above issue?

I've tested it with nvidia-drivers on my gentoo machine so I can confirm :)

**Comment by scardracs** [comment]
Uhm, I've re-read the error in the image and seems not related to others. The best solution is to set chmod 4775 to chrome-sanbox and chown root:root as required on the image. Saying that, --no-sandbox is still not a good solution
