### ISSUE TITLE
Cannot access Windows taskbar that's on auto-hide when Terminus is maximised

### ISSUE THREAD

**Issue by Southclaws** [Eugeny/terminus#2671]
I put my taskbar at the top and auto-hide it - don't ask why, just how I've always had Windows set up ever since 98.

There's a really silly bug in a lot of software that makes the taskbar inaccessible when the app is full-screen. I'm not entirely sure but it's something to do with custom window frames (  https://docs.microsoft.com/en-us/windows/desktop/dwm/customframe) when sized to the screen size and being drawn over the trigger zone for showing a hidden taskbar. (a lot of software tries to implement its own "maximise" feature with frameless windows and it's never perfect)

This issue was also raised in VS Code: https://github.com/microsoft/vscode/issues/81102 and there's a clip demonstrating the problem:

![https://user-images.githubusercontent.com/1937871/68553386-f9f3cf80-0463-11ea-87de-1add51a5164f.gif](https://user-images.githubusercontent.com/1937871/68553386-f9f3cf80-0463-11ea-87de-1add51a5164f.gif)

I'm not familiar with Electron otherwise I'd try and solve it, but it seems like a problem that's been solved elsewhere so that gives me hope that I can maximise Terminus instead of resizing the window to _almost_ fullscreen!

**Comment by Eugeny** [comment]
Thanks for the detailed report. Are you on the latest release? According to the vscode ticket, it's fixed in Electron version we're using.

**Comment by Southclaws** [comment]
Yes I was confused at that because it claims it was fixed but none of my Electron applications have caught the fix. Terminus is at 1.0.111 and it's still happening.

The user-side solution for VS Code was to set `"window.titleBarStyle": "native",` which disables the seamless one-colour custom window frame and uses the default normal window chrome, not sure if that might help here. I'd be happy with Terminus using standard window chrome for the title bar if it solved this problem tbh.

![image](https://user-images.githubusercontent.com/1636971/83925359-e0f39880-a77e-11ea-84b7-e3cb72c5d954.png)

**Comment by Eugeny** [comment]
You can set Terminus to use the native window frame from Settings -> Application -> Window frame.

**Comment by Southclaws** [comment]
Ah, didn't know that setting existed, thanks!

I'll leave that as resolved then as I'm happy with the solution and I'm pretty sure this is the electron bug and it wasn't fixed after all (both apps with the issue are still after the supposedly fixed electron version so... 🤷‍♀️)

**Comment by Onepamopa** [comment]
It would be nice if "thin" frame also worked with auto-hide taskbar...
