### ISSUE TITLE
Window not quite fitting screen

### ISSUE THREAD

**Issue by shaqaruden** [Eugeny/terminus#3263]
Not sure if you can fix this. I have a 4K main display with a 1080P secondary display. When Terminus is maximized on the 4K display and acrylic background is enabled, I get the edge of the window on the 1080P display. I realize this would not be near as noticeable if the displays were the same resolution.

![image](https://user-images.githubusercontent.com/5414897/103232329-2ab4f380-4908-11eb-9304-a2d9a863e6fe.png)

Version: 1.0.123
Platform: Windows 10 2004

**Comment by shaqaruden** [comment]
a little bit info. This only happens when the window is maximized, fitting the window into 1 half of my 4K display does not cause the issue

**Comment by aidenmitchell** [comment]
It's an Electron issue, but it should be fixed? https://github.com/electron/electron/pull/25940

**Comment by Eugeny** [comment]
Good catch - it's fixed in the Electron 12 beta - I'll upgrade once it's stable

**Comment by Onepamopa** [comment]
@Eugeny I don't know if you've upgraded Electron version ... but the blurred edges are still there @ latest terminus version.
Please reopen issue and close once its fixed.

**Comment by Eugeny** [comment]
This issue is still open.

**Comment by Eugeny** [comment]
We're on Electron 12 now - please reopen if the issue is still there.

**Comment by shaqaruden** [comment]
@Eugeny thisbis still an issue in the latest Tabby build. Did you upgrade to Electron 12?

**Comment by shaqaruden** [comment]
I still see this issue with the latest version of Tabby

**Comment by shaqaruden** [comment]
This is still an issue on 167

![image](https://user-images.githubusercontent.com/5414897/145438739-f48ed75b-0980-4787-b6b6-e4faf5d539d1.png)

**Comment by shaqaruden** [comment]
Still an issue on Tabby 167

![image](https://user-images.githubusercontent.com/5414897/145439050-4136f022-46ec-4b4c-9165-572311c26308.png)

**Comment by shaqaruden** [comment]
> Still an issue on Tabby 167
> 
> ![image](https://user-images.githubusercontent.com/5414897/145439050-4136f022-46ec-4b4c-9165-572311c26308.png)

@Eugeny
