### ISSUE TITLE
Ligatures broken after update

### ISSUE THREAD

**Issue by malaverdiere** [Eugeny/terminus#778]
Version: 1.0.75 
Platform: Windows 10
Font: Fira Code
Plugin: SSH
Frontend: `xterm`

Terminus outputs weird gaps when rendering git tags and paths. Closing and restarting all tmux sessions had no effect. Disabling ligatures resolved the issue.

Please note that the issue does not reproduce using `hterm` and enabling ligatures.

**Comment by Eugeny** [comment]
Upstream https://github.com/xtermjs/xterm.js/issues/2028

**Comment by Adrian-Grimm** [comment]
Lineaturen does also not work here on MacOS with xterm.
hterm works but there are other things broken...

Font: Operator Mono +Lineaturen +NerdFont patched
Version: 1.0.77
Platform: darwin 18.5.0
Plugins: clickable-links, scrollbar, title-control

**Comment by Eugeny** [comment]
fixed in the nightly builds

**Comment by dogik** [comment]
@Eugeny Thanks for all your work. I was curious if ligatures and the outlined issue were fixed in https://github.com/Eugeny/terminus/releases/tag/v1.0.78 ?

I have just updated to that version, but still having issues on xterm with ligatures. I am using Fira Code and it does work with hterm. Thanks.

**Comment by Eugeny** [comment]
@dogik - yes - I'm using xterm frontend with Fira Code myself :)
Which OS are you on?

**Comment by dogik** [comment]
@Eugeny thanks. I am on windows 10 1809. Remote - ubuntu 19.

Weird thing is that I have 3 PCs - two have 1809 and one has fresh 1903. On one of those (which is 1809) ligatures work fine on xterm. I was trying to figure out what is the difference, but couldn't find anything. I copied terminus config file accross all PCs.

I will play around more and let know if I can find what is wrong. Thanks.

**Comment by oocx** [comment]
![image](https://user-images.githubusercontent.com/584396/63183147-93256c80-c054-11e9-9e4e-5b403f1ef46e.png)

Ligatures only work with hterm for me (see screenshot - xterm on the left, hterm on the right).

Terminus 1.0.88
Windows 10 1903 build 18950 (fast ring)
Fira Code

**Comment by odalet** [comment]
Same thing here: ligatures with Fira Code only work in hterm (but then I loose blinking and underlined cursor). 
Using Terminus 1.0.105
Windows 10 1909 (18363.720)

**Comment by Eugeny** [comment]
@odalet are you using the xterm or xterm-webgl frontend? xterm-webgl doesn't support ligatures yet.

**Comment by odalet** [comment]
Sadly, I'm using the xterm engine.

**Comment by wrvsrx** [comment]
I meet the problem too. I use xterm engine and get the same result. And hterm engine works well.

**Comment by himejisyana** [comment]
I'm using the xterm engine and I meet the problem too.

**Comment by himejisyana** [comment]
But when I changed the font and switched back to `Fira Code` again, the problem waas solved.

**Comment by retsimx** [comment]
Win 10 here. Similar problem. No combination of fonts with ligatures work with xterm (or xterm-webgl, indicated above as not implemented).

Fonts with ligatures only appear to work for me with hterm which is by no means a deal breaker for me.
