### ISSUE TITLE
sudo not working on Linux

### ISSUE THREAD

**Issue by marcinbojko** [Eugeny/terminus#960]
Version: 1.0.78
Platform: linux 4.18.0-13-generic
Plugins: altair, clickable-links, quick-cmds, save-output, scrollbar, shell-selector, theme-gruvbox, title-control

Possible regression with sudo:
```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

**Comment by elielam** [comment]
Same here !

Ubuntu 18.04
Terminus 1.0.78

**Comment by raphaelriehl** [comment]
Same issue and same config as @elielam.

**Comment by xingchenyefeng** [comment]
Same here !

Ubuntu 18.04
Terminus 1.0.78

**Comment by mrpatg** [comment]
Same issue

Ubuntu 19.04
Terminus 1.0.78

**Comment by ozlevka-ericom** [comment]
Have the same
Ubuntu 19.04
Terminus 1.0.78

**Comment by lwyj123** [comment]
Same here !

Ubuntu 18.04
Terminus 1.0.78

**Comment by NieLeben** [comment]
Same issue here

ArchLinux 5.1.5-arch1-2-ARCH
Terminus 1.0.78

**Comment by NonStatic2014** [comment]
Same here. Any workaround?

Ubuntu 16.04
Terminus 1.0.78

**Comment by mrpatg** [comment]
I went with the previous release and didn't have the same issue there.

**Comment by NonStatic2014** [comment]
Thank you to @mrpatg 

The current workaround would be rolling back to 1.0.77. In the meanwhile, 1.0.79 still has this issue.

**Comment by melonwool** [comment]
Same issue here

Deepin GNU/Linux 15.10.1 
Terminus 1.0.79

**Comment by MaXZon3** [comment]
Same here.

Linux Mint 19.1

**Comment by NieLeben** [comment]
The problem seem to be electron v5.
https://github.com/electron/electron/issues/18521

**Comment by RafaelGondi** [comment]
Same issue here.

Version: 1.0.80
Platform: linux 4.18.0-21-generic

**Comment by hcodhsing** [comment]
Same issue here.

Version: 1.0.80
Platform: gentoo x86_64 Linux 5.1.7

**Comment by KubrikDevelopmentStudio** [comment]
Same issue here.

Version: 1.0.81
Platform: linux 4.19.10-041910-generic

**Comment by Paulpatou** [comment]
Same issue here.

Version: 1.0.81
Platform: Linux 4.15.0-51-generic  / Ubuntu 16.04

**Comment by ilkerhalil** [comment]
Same here !
Ubuntu 18.04
Terminus 1.0.78

**Comment by Undomyr** [comment]
Same issue.

Version: 1.0.82
Platform: Linux 5.1.8-1-Manjaro

**Comment by kankaristo** [comment]
If you're using tmux (screen may also work?), here's another workaround:
1. Launch a new tmux session in some other terminal program (e.g. gnome-terminal)
2. Detach from the session
3. Attach to the session in Terminus

...and sudo works (probably because sudo is not a child process of Terminus/Electron, but of the tmux server).

Any new tmux window or session (started from within this session) will also have working sudo.

**Comment by an333** [comment]
Same issue here.

Version: 1.0.87
Platform: Linux Mint 19.1 & KDE neon 15.6

**Comment by juanmaioli** [comment]
Same issue here

Deepin GNU/Linux 15.11
Terminus 1.0.87

**Comment by mattisdada** [comment]
I am also experiencing this for the last few reasons
Terminus 1.0.87
Fedora Workstation 30

**Comment by jamezpolley** [comment]
> If you're using tmux (screen may also work?), here's another workaround:

As another alternative, you can `ssh localhost`. That spawns a new shell that's not a child of Terminus/Electron, so you can sudo from there.

**Comment by ElDarco** [comment]
Same issue here.

Version: 1.0.87
Platform: Linux Mint 19.1

**Comment by reecebenson** [comment]
Same issue here.

Version: 1.0.87
Platform: Ubuntu 18.04.1 LTS

**Comment by AngFl** [comment]
Ubuntu Meta 18.04

```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

**Comment by Kenryoj** [comment]
Same issue and output as @AngFl
Version: 1.0.87
Platform: Pop!_OS 18.04

**Comment by NuSkooler** [comment]
The "+1"'s are piling up, I think they get it guys :)

Question for maintainers: What's the status on this? I think not being able to perform `sudo`-ish commands in Linux generally makes the terminal useless there :(

**Comment by Eugeny** [comment]
@nuskooler it's currently blocked by  https://github.com/electron/electron/issues/18521 , so I'm waiting for the Electron to react. Unfortunately it doesn't seem that there is a workaround without them actually fixing this.

**Comment by KsRyY** [comment]
So is there any way to do `sudo` inside terminus? I'm experiencing the same issue.

Version:1.0.88
OS: deepin 15.11

**Comment by KsRyY** [comment]
I am not sure if you use a pty like `node-pty` instead of the built in `child_process` would work.

**Comment by an333** [comment]
Sorry for my English. The latest working version for Linux was 1.0.77, all subsequent ones, including 1.0.88, do not work correctly with SUDO. What is the point of releasing versions for Linux if the main function does not work in them?

**Comment by KsRyY** [comment]
Trying to implement terminus in `node-pty`

**Comment by KsRyY** [comment]
I am trying to make it work.

**Comment by KsRyY** [comment]
> Sorry for my English. The latest working version for Linux was 1.0.77, all subsequent ones, including 1.0.88, do not work correctly with SUDO. What is the point of releasing versions for Linux if the main function does not work in them?

I thought the releasing progress may be automated, the author may not want to ruin the automation so he kept the default releasing.

**Comment by KsRyY** [comment]
@Eugeny Could you try to use something like `node-pty` in Terminus? This library may help.

**Comment by Eugeny** [comment]
@ksryy Terminus is using node-pty. Please see my previous reply regarding the upstream bug in Electron

**Comment by desenvolvedorfmais** [comment]
Mint 19.1 ~ 19.2
Versão: 1.0.79
sudo with Terminus running sudo only on version 1.0.79 or lower.
Versions 1.0.80 or higher not working sudo

#PT BR
sudo com o Terminus funcionando o sudo somente na versão 1.0.79 ou inferior.
Versões 1.0.80 ou superior não funcionando o sudo

**Comment by Eugeny** [comment]
I'm pleased to announce that sudo and other setuid commands now work in Alpha 91

**Comment by elijah-rou** [comment]
Hi! I'm still getting this issue in the latest release (92).

Pop_OS! 19.10
Terminus 1.0.92

`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

**Comment by Paulpatou** [comment]
Same issue with Terminus 1.0.97  `sudo: le uid effectif n'est pas 0. Est-ce que /usr/bin/sudo est sur un système de fichiers avec l'option « nosuid » ou un système de fichiers NFS sans privilèges root ?`

**Comment by iggz** [comment]
Just install ubuntu 18.04.3 LTS this morning and killed all morning on this issue. Cant find a solution anywhere. 

iggz@iggz-ub:~$ su -
Password: 
su: Authentication failure
iggz@iggz-ub:~$ sudo -i
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

**Comment by patjgardner** [comment]
Same problem with Fedora 31. Looking into the problem I read this [https://github.com/electron/electron/pull/19953](url) which mentions that the electron fix only applies to unsandboxed. So running 'terminus --no-sandbox' allows me to successfully run sudo in the shell without the error.

**Comment by archit120** [comment]
This doesn't seem to be working for me. I'm on 1.0.98, Ubuntu 18.04 

I'm using the bash terminal which might be the cause.

**Comment by mattisdada** [comment]
This issue was resolved for me for a while, but just updated (alpha 103) and it has reappeared once more :( 

Running Fedora 31, zsh 5.7.1 (x86_64-redhat-linux-gnu)

**Comment by patjgardner** [comment]
I've updated to 1.0.103 (also on Fedora 31) using the Linux RPM and don't have the issue  @mattisdada is reporting. I've tried sudo in both bash and zsh and it still works as expected for me.

**Comment by mattisdada** [comment]
@patjgardner Thanks for trying to replicate :) 

I rebooted my machine after hearing you weren't having any issues, and the problem resolved itself. There must have been an issue during the upgrade because I still had the older Terminus running (101 maybe?) and maybe it didn't properly shutdown

You can probably close this again @Eugeny, sorry for raising a false alarm! I should've rebooted before reporting

**Comment by jorepstein** [comment]
I was experiencing this issue again on Ubuntu 18.04.4. Then I realized I had the alpha (105) installed so I installed 104 instead, and the problem seems to have been fixed.

**Comment by guschinaglia** [comment]
Same in OpenSUSE

**Comment by boistordu** [comment]
it's happening to me again in fedora 32 with alpha 115
`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

**Comment by rahacker2006** [comment]
Same in Ubuntu 20.04

**Comment by pauldadin** [comment]
Same here in ubuntu 20.04

**Comment by stefangweichinger** [comment]
happens again today with terminus-125 on Fedora 33

**Comment by Tbhesswebber** [comment]
I'm seeing this on a fresh install of Ubuntu 20.04.  I am still primarily using alternative emulators because the fact that this happens intermittently is making it so I can't fully shift over

**Comment by RisksY** [comment]
EndeavourOS
Linux risksypc 5.11.2-arch1-1
Terminus v1.0.134

```
$ sudo su
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```
<br>
<br>
sudo works in Alacritty, Konsole and xterm without any problem but doesn't work in Terminus. Only works when I use tmux.

**Comment by pythoninthegrass** [comment]
## Environment
Debian 10 Buster
Linux nuc 5.4.78-2-pve (Proxmox)
Terminus v1.0.135 (Windows 10 21318.1000)

## Issue
sudo doesn't work with either `sudo su` or `sudo -s` raising `sudo: 1 incorrect password attempt` while I'm able to ssh into the same host from cmder (ConEmu) and escalate privileges without issue.

**Comment by shivdhwaj** [comment]
Ubuntu 20.10
Terminus 1.0.135
sudo - command not working
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

**Comment by Eugeny** [comment]
Please also include which installation method you're using (.deb / .tgz / Snap)

**Comment by shivdhwaj** [comment]
I have used .deb file

**Comment by RK-githug** [comment]
Ubuntu 20 with terminus1.0.139.
I had this issue after first time install + setup which got me worried because I liked what I saw.
The resolve was just a simple restart for me, not sure what went wrong but it is possible it scared off some new users

**Comment by pacharanero** [comment]
Same problem on 1.0.143
Linux Mint 20.1 Cinnamon, Kernel 5.8
.deb install

**Comment by pacharanero** [comment]
Sorry, I 'issued' too soon. If you reboot the machine, this seems to solve the problem.

**Comment by howar31** [comment]
Still having the issue

Ubuntu 20.04
Tabby 1.0.155

restart Tabby will fix this issue but it'll happen again later

**Comment by rapha8l** [comment]
Same for me on Void linux with last release 1.0.157

**Comment by rapha8l** [comment]
to update my comment, I'm using the tgz

**Comment by Lateralus138** [comment]
I used the latest deb installer: [[`tabby-1.0.158-linux.deb`](https://github.com/Eugeny/tabby/releases/download/v1.0.158/tabby-1.0.158-linux.deb)] to install on **Ubuntu 20.04** using

```Bash
sudo dpkg -i Downloads/tabby-1.0.158-linux.deb
```
in a different terminal  and it threw an error, but only because of broken dependencies, no big deal, fixed with a `sudo apt --fix-broken` and it now runs fine, but it has this issue when trying to run sudo like everyone else here.

I'm liking this terminal so far and it was starting to look better than another one I'm using so I was getting my hopes up until this happened, but this is a big deal. I use sudo often. I love that I have more CSS control though, by the way.

I'll look into this issue at some point.

**Comment by CoconutMacaroon** [comment]
I can confirm this:
Mode: Downloaded `.deb` from GitHub
Tabby Version: 1.0.161
OS: Ubuntu Desktop 21.10

**Comment by rapha8l** [comment]
Strange that such a big issue remains unanswered even for a "I don't care"

**Comment by CoconutMacaroon** [comment]
> Strange that such a big issue remains unanswered even for a "I don't care"

Someone noted that you can `ssh localhost`. This isn't ideal, as constantly using that is annoying. However, I realized that you can tell Bash to always proxy `sudo` over SSH.

Add the following to your `~/.bashrc` file:
```sh
alias sudo="ssh $(whoami)@localhost sudo
```
It will 'fix' `sudo`,so that all `sudo` commands will be ran over SSH. If you don't want to use a password every time, you can setup an SSH key.

**Comment by CoconutMacaroon** [comment]
> Strange that such a big issue remains unanswered even for a "I don't care"

(1) If it is so important to you, send a PR with a fix. Tabby is open-source, after all.
(2) Someone noted that you can `ssh localhost`. This isn't ideal, as constantly using that is annoying. However, I realized that you can tell Bash to always proxy `sudo` over SSH, so everything To do this, add the following to your `~/.bashrc` file:
```sh
alias sudo="ssh $(whoami)@localhost sudo"
```
It will 'fix' `sudo`,so that all `sudo` commands will be ran over SSH. If you don't want to use a password every time, you can setup an SSH key.

**Comment by Eugeny** [comment]
> Strange that such a big issue remains unanswered even for a "I don't care"

@rapha8l I care a lot for everybody who has issues using my app, however I can't afford to run around posting as much as dedicated project managers in other projects can. There are 500+ open issues and only so much of my free time I can dedicate to working on it.

The reason this hasn't been fixed for so long is that I'm unable to reproduce it on any of my Linux boxes.

There has already been a similar bug in the past, but that was caused due to Chromium's own sandboxing preventing SUID binaries (here, sudo) from getting spawned, but that's been fixed.

Unfortunately the sudo's error message is not helpful at all and without a viable repro, I have no idea where to start.

**Comment by CoconutMacaroon** [comment]
> The reason this hasn't been fixed for so long is that I'm unable to reproduce it on any of my Linux boxes.
> 
> There has already been a similar bug in the past, but that was caused due to Chromium's own sandboxing preventing SUID binaries (here, sudo) from getting spawned, but that's been fixed.
> 
> Unfortunately the sudo's error message is not helpful at all and without a viable repro, I have no idea where to start.

@Eugeny 

Of course, if you are busy, I totally understand. That said, here is exactly what I did to reproduce the issue:
1. Download Ubuntu 21.10 from [the Ubuntu website](https://ubuntu.com/download/desktop)
2. Install it onto a 64 bit machine (using the LiveCD might work, I don't know, but you could try)
3. Download updates (`sudo apt update && sudo apt upgrade`)
4. Download the latest `.deb` from [the Releases](https://github.com/Eugeny/tabby/releases)
5. Install the `.deb` with `sudo apt install ./tabby-1.0.XYZ-linux.deb`
> It is important that you install with `sudo apt install ./file.deb` instead of `sudo dpkg -i ./file.deb`. The second one does different things
6. Launch Tabby
7. Type in `sudo` (by itself), and press enter. Observe that it fails

**Comment by rapha8l** [comment]
Hi, to be clear, I didn't meant to be rude
It's a personnal open source project, and you manage your time as you can, and we can all thank you for what you did
Your answer is totally clear and understandable

**Comment by marcinbojko** [comment]
I haven't had this issue for a long, long long time.

**Comment by RK-githug** [comment]
Me too, today I upgraded to 161 from 139 (no issues whatsoever). I also tried to replicate the sudo issue on a VM: fresh Ubuntu 20.04 with Tabby 161 via .deb and I had no issues anymore

**Comment by Eugeny** [comment]
@CoconutMacaroon sorry, it just works for me: 
![image](https://user-images.githubusercontent.com/161476/140197320-3bb2d305-40b0-4fb4-aca2-0588186d0f72.png)

**Comment by rapha8l** [comment]
works for me now, thanks

**Comment by svallory** [comment]
Just download the `.deb` for `1.0.162`, running on Zorin 16 and when I try `sudo` I get this:

```
~ 
➜ sudo su
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

**Comment by janiktest** [comment]
quick restart fixed it for me

**Comment by Lateralus138** [comment]
> quick restart fixed it for me

Same for me as stated above, but it took 2 or 3 restarts.

**Comment by freeNestor** [comment]
Same issue here, some circumstance causes this we don't known. 
I suppose it relates to libldap library, because this problem appears several times after my system was upgraded and I messed some libraries for solving another problem , so I restored some libraries and downgrade libldap, this issue doesn't occur  a period of time. Hope this may help someone and developers, I'm not sure. I'll keep watching if it disappears. 
Workaround is restarting it.

**Comment by Guztaver** [comment]
Same issue, i have solved disabling "Encrypt config file", in vault settings, and Restarted the terminal. 

 OS: Pop OS 21.10
 Mode: GitHub `.deb` downloaded with `wget`, installed with `dpkg`
 Tabby Version: `1.0.168`

**Comment by jonnyhoff** [comment]
This issue happened intermittently.

When exiting Tabby the  below processes still run in the background.

```bash
$ ps -eaf|grep tabby
user    7570    3731  0 Dec20 ?        00:00:00 /opt/Tabby/tabby --type=zygote --no-zygote-sandbox --no-sandbox
user    7571    3731  0 Dec20 ?        00:00:00 /opt/Tabby/tabby --type=zygote --no-sandbox
```

After killing these I'm able to use `sudo`

```bash
pkill tabby
```

OS: Fedora 35

**Comment by maxreuben** [comment]
The same issue is present in Fedora 34(Linux 5.15.10-100.fc34.x86_64). Killing the app and restarting did fix it.

> This issue happened intermittently.
> 
> When exiting Tabby the below processes still run in the background.
> 
> ```shell
> $ ps -eaf|grep tabby
> user    7570    3731  0 Dec20 ?        00:00:00 /opt/Tabby/tabby --type=zygote --no-zygote-sandbox --no-sandbox
> user    7571    3731  0 Dec20 ?        00:00:00 /opt/Tabby/tabby --type=zygote --no-sandbox
> ```
> 
> After killing these I'm able to use `sudo`
> 
> ```shell
> pkill tabby
> ```
> 
> OS: Fedora 35

**Comment by albertoglezba** [comment]
> @CoconutMacaroon sorry, it just works for me: ![image](https://user-images.githubusercontent.com/161476/140197320-3bb2d305-40b0-4fb4-aca2-0588186d0f72.png)

I have these errors with sudo:

```
sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.

```
I think I found a way to replicate them...

![image](https://user-images.githubusercontent.com/5861322/167097821-1d0e3587-182d-4475-8cd0-ad510a2178b2.png)

Whenever Tabby asked me to restart application in order to changes to take effect, I click on that yellow bar, application restart, but suddenly sudo stops working.
As pointed out above, killing all process and start Tabby again fix the issue (because exit from toolbar wont kill the PIDs), but it reappears whenever it restarts from that yellow bar.

**Comment by RadarExile** [comment]
> @albertoglezba this is a great find! Does everybody else have the same problem only when restarting from Settings? Or are there other cases where sudo stops working?

It's the same for me; If I restart from the yellow bar in settings, sudo breaks. If I close and restart normally, everything works.

**Comment by Eugeny** [comment]
Please check whether this build fixes the issue: https://github.com/Eugeny/tabby/actions/runs/2336887615

**Comment by albertoglezba** [comment]
> Please check whether this build fixes the issue: https://github.com/Eugeny/tabby/actions/runs/2336887615
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[set --no-sandbox when relaunching on Linux · Eugeny/tabby@f1d9116](https://github.com/Eugeny/tabby)**A terminal for a more modern age. Contribute to Eugeny/tabby development by creating an account on GitHub.

Sorry Eugeny, no fix for me, still sudo broken

![Captura desde 2022-05-18 23-25-06](https://user-images.githubusercontent.com/5861322/169209823-7295da1e-4710-4df6-96ec-b8779f054a3b.png)

--no-sandbox is set but sudo still not working after restart

![Captura desde 2022-05-18 23-18-56](https://user-images.githubusercontent.com/5861322/169210164-3a64d597-ba59-4c5b-804e-9ae990fd968a.png)

**Comment by TimaGribanov** [comment]
>Does everybody else have the same problem only when restarting from Settings? Or are there other cases where sudo stops working?

Met this today on 1.0.182 (Ubuntu 22.04.1 LTS). Never had this issue before, but after clicking on the yellow bar to restart it appeared.

Re-opened Tabby the usual way, and sudo works perfectly.

**Comment by skqist225** [comment]
> > If you're using tmux (screen may also work?), here's another workaround:
> 
> As another alternative, you can `ssh localhost`. That spawns a new shell that's not a child of Terminus/Electron, so you can sudo from there.

I don't even know we can use ssh with localhost, but it works perfectly. Thank you

**Comment by lolomin** [comment]
Same problem here for me under Fedora 37, Tabby restarted through the Yellow bar and sudo or su did not work anymore.After killing all Tabby processes manually : sudo or su - is working back as normal.

**Comment by refactorized** [comment]
hey just came here via google to check why my new fav term seems to be in sandbox mode, but I too had just restarted via settings.  A quick `killall tabby` (from within tabby itself, which feels... awkward) fixed it right up!

**Comment by wurenny** [comment]
**So in the end:** the problem is caused by the yellow restart bar(when you update some config that need restart).
because tabby processes do not all exit before restart
**The solution is a manual restart once again**

**Comment by sunTFly** [comment]
Manually restart the computer
